###################################################
#------- General Push Server Configuration -------#
###################################################

#This is the port that the push server will be on.
#443 is usually a wise choice, as most people/companies will
#open that on their firewall.
PUSH_PORT: 20443

#This is the host that the push server will be on.
#Usually it would be 0.0.0.0
PUSH_HOST: "0.0.0.0"

#Channels on which juggernaut will broadcast by default.
DEFAULT_CHANNELS:
 - "default_channel"

#This should be the url as seen from the browser.
#Flash's xmlsocket can only connect to addresses in the same domain
#or subdomain. For example, if people access your app from www.test.com than this
#should be "test". Omit the port number and the 'http://'.
PUSH_HELPER_HOST: "localhost"

#This is a 'secret' send by the broadcaster to validate identity.
SECRET: "2987v9ckq28zkc8vjne38fkdj"

###################################################
#------- Client Side Configuration (Flash) -------#
###################################################

# At the moment the next two methods aren't used, they will be in the future.

#This is the number of tries the xmlsocket will try and reconnect with the server when disconnected
NUM_TRIES: 3

#This is amount of seconds between each TRY
NUM_SECS: 3

#########################
#------- Logging -------#
#########################

# Display a text log in the push server console. Exceptions are always shown
LOG_SCROLL: true

# Adds log information to a text file in the log dir.
LOG_TEXT: true

###########################################
#------- Authentication (optional) -------#
###########################################

# When the two requests below get called, the session id of the client is used - so it looks (to Rails) like a request from the client.

# Triggered called on connect. Know that this will trigger on page refreshes as well (which is a good reason to limit them); 
# meaning a disconnect...then connect will happen.
# The channels and unique id (if provided) of the client are also sent as parameters, 'unique_id' and 'channels' reseptively (channels is an array).
# It's a good idea to check these two for security reasons. Failed authentication should return a 401 status code, if it passes just return a 200.
#LOGIN_GET_URL: "http://localhost:3000/sessions/juggernaut_login"

# Triggered on client disconnect from push. You can use this to know when clients leave ( and update statuses etc if necessary ).
#LOGOUT_GET_URL: "http://localhost:3000/sessions/juggernaut_logout"

# This is the app session id (define in enviroment.rb for edge, and in application.rb for the current Rails version)
SESSION_ID: "_session_id"

######################
#------- Misc -------#
######################

# Toggle base64 encoding. If you are having troubles with escaping strings, try turning it on.
BASE64: true

